### ISSUE TITLE
使用我自己的coco数据集训练时报错

### ISSUE THREAD

**Issue by dqq813** [fh2019ustc/PolySnake#5]
Random Seed: 123
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
loading annotations into memory...
Done (t=0.75s)
creating index...
index created!
loading annotations into memory...
Done (t=0.21s)
creating index...
index created!
train: Epoch: 0
eta: 0:04:35  epoch: 0  step: 100  mask_loss: 1.1265  ct_loss: 9.9765  wh_loss: 0.4440  py_loss: 2.4523  shape_loss: 0.1815  loss: 14.1808  data: 0.0084  batch: 0.5586  lr: 0.000100  max_mem: 3470
eta: 0:03:43  epoch: 0  step: 200  mask_loss: 0.7927  ct_loss: 3.3213  wh_loss: 0.3655  py_loss: 2.0679  shape_loss: 0.0886  loss: 6.6360  data: 0.0091  batch: 0.5620  lr: 0.000100  max_mem: 3983
eta: 0:02:48  epoch: 0  step: 300  mask_loss: 0.6213  ct_loss: 1.8973  wh_loss: 0.3333  py_loss: 1.8896  shape_loss: 0.0981  loss: 4.8396  data: 0.0089  batch: 0.5571  lr: 0.000100  max_mem: 3983
eta: 0:01:52  epoch: 0  step: 400  mask_loss: 0.5399  ct_loss: 1.5056  wh_loss: 0.3269  py_loss: 1.8097  shape_loss: 0.0957  loss: 4.2778  data: 0.0095  batch: 0.5528  lr: 0.000100  max_mem: 3983
eta: 0:00:57  epoch: 0  step: 500  mask_loss: 0.5813  ct_loss: 1.4105  wh_loss: 0.3498  py_loss: 1.9747  shape_loss: 0.0853  loss: 4.4016  data: 0.0090  batch: 0.5660  lr: 0.000100  max_mem: 3983
eta: 0:00:01  epoch: 0  step: 600  mask_loss: 0.5160  ct_loss: 1.2015  wh_loss: 0.3157  py_loss: 1.6819  shape_loss: 0.0782  loss: 3.7933  data: 0.0087  batch: 0.5563  lr: 0.000100  max_mem: 3983
eta: 0:00:00  epoch: 0  step: 601  mask_loss: 0.5110  ct_loss: 1.2021  wh_loss: 0.3062  py_loss: 1.6261  shape_loss: 0.0758  loss: 3.7213  data: 0.0089  batch: 0.5551  lr: 0.000100  max_mem: 3983
train: Epoch: 1
eta: 0:04:41  epoch: 1  step: 702  mask_loss: 0.5021  ct_loss: 1.1397  wh_loss: 0.3219  py_loss: 1.7633  shape_loss: 0.0737  loss: 3.8006  data: 0.0090  batch: 0.5616  lr: 0.000100  max_mem: 3983
eta: 0:03:45  epoch: 1  step: 802  mask_loss: 0.4449  ct_loss: 0.9661  wh_loss: 0.2698  py_loss: 1.3796  shape_loss: 0.0610  loss: 3.1214  data: 0.0095  batch: 0.5578  lr: 0.000100  max_mem: 3983
eta: 0:02:49  epoch: 1  step: 902  mask_loss: 0.4310  ct_loss: 0.9317  wh_loss: 0.2606  py_loss: 1.3552  shape_loss: 0.0574  loss: 3.0360  data: 0.0093  batch: 0.5731  lr: 0.000100  max_mem: 3983
eta: 0:01:53  epoch: 1  step: 1002  mask_loss: 0.4756  ct_loss: 0.9769  wh_loss: 0.2400  py_loss: 1.2478  shape_loss: 0.0495  loss: 2.9897  data: 0.0104  batch: 0.5537  lr: 0.000100  max_mem: 4003
eta: 0:00:57  epoch: 1  step: 1102  mask_loss: 0.4366  ct_loss: 0.9670  wh_loss: 0.2900  py_loss: 1.4717  shape_loss: 0.0617  loss: 3.2271  data: 0.0092  batch: 0.5532  lr: 0.000100  max_mem: 4003
eta: 0:00:01  epoch: 1  step: 1202  mask_loss: 0.4228  ct_loss: 0.8414  wh_loss: 0.2606  py_loss: 1.3517  shape_loss: 0.0602  loss: 2.9368  data: 0.0092  batch: 0.5544  lr: 0.000100  max_mem: 4003
eta: 0:00:00  epoch: 1  step: 1203  mask_loss: 0.4333  ct_loss: 0.8418  wh_loss: 0.2695  py_loss: 1.4012  shape_loss: 0.0611  loss: 3.0070  data: 0.0095  batch: 0.5544  lr: 0.000100  max_mem: 4003
  5%|██████▎                                                                                                                    | 17/329 [00:04<01:01,  5.09it/s]
Traceback (most recent call last):
  File "train_net.py", line 83, in <module>
    main()
  File "train_net.py", line 74, in main
    train(cfg, network)
  File "train_net.py", line 59, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/home/dqq/project/PolySnake/lib/train/trainers/trainer.py", line 82, in val
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/snake.py", line 24, in forward
    output = self.net(batch['inp'], batch)
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 22, in forward
    output = self.raft(output, cnn_feature, batch)
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ICD.py", line 96, in forward
    net, offset = self.update_block(net, i_poly_fea)
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/update.py", line 35, in forward
    net = self.gru(net, i_poly_fea)
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/update.py", line 14, in forward
    z = torch.sigmoid(self.convz(hx))
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dqq/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 128 3, expected input[0, 2, 2] to have 128 channels, but got 2 channels instead

**Comment by uu88s** [comment]
It could be that your data set is not formatted correctly

**Comment by LiuReboot** [comment]
请问正确的coco数据集格式是怎样的呢？能给出数据集的目录结构吗

**Comment by ZitengXue** [comment]
您好我也遇到了这个问题，请问您解决了吗？
